### ISSUE TITLE
barcode list

### ISSUE THREAD

**Issue by ndu-UCSD** [sandberg-lab/Smart-seq3#1]
Hi I am wondering for paired end sequence how do you format the expected_barcodes.txt? Thanks

**Comment by cziegenhain** [comment]
Hi,

The expected_barcodes.txt always has the same format, independent of sinlge-end/paired-end sequencing. 
For more information on barcode handling in zUMIs, please read the relevant page in the zUMIs wiki: https://github.com/sdparekh/zUMIs/wiki/Barcodes
