### ISSUE TITLE
The length of i5/i7 index in HCA data

### ISSUE THREAD

**Issue by PeiyuShii** [sandberg-lab/Smart-seq3#13]
Hello!  Thanks for developing SMART-seq3, such a wonderful single cell sequencing technique. I would like to reanalyze Smart-seq3 data of HCA reference sample. I find that the sequence length in HCA.I1.fastq.gz and HCA.I2.fastq.gz is 10bp. However, the protocol of SMART-seq3 (https://teichlab.github.io/scg_lib_structs/methods_html/SMART-seq_family.html#SMART-seq3) mentions that 8-bp i5/i7 index are used in SMART-seq3 library. What length should I set in zUMIs yaml config file to recognize barcode, 8bp or 10bp?  Thanks for your help!

**Comment by cziegenhain** [comment]
Hi,

Smart-seq3 could be used with 8 or 10 bp indices. In terms of the data we have deposited that you mention, it is 10 bp barcodes.

**Comment by PeiyuShii** [comment]
Thanks for quick reply! Besides, I noticed that there a file named `expected_barcodes.txt` in https://github.com/sandberg-lab/Smart-seq3/blob/master/allele_level_expression/mouse_cross.yaml. How can I find the information of expected barcodes in Smart-seq3? Or it isn't needed since zUMIs will perform automatic cell barcode selection?

**Comment by cziegenhain** [comment]
The data submissions at ArrayExpress contains sample annotation from which you can take the expected barcodes!
It is usually best practice to provide the barcodes to zUMIs, even though you could also try automatic selection

**Comment by PeiyuShii** [comment]
Got it. Thanks a lot!
