### ISSUE TITLE
About repeating the analysis of HEK293T

### ISSUE THREAD

**Issue by yewero** [sandberg-lab/Smart-seq3#2]
I would like to repeat the analysis of Smart-seq3 (HEK293T) (the second sample at https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8735/samples/). However, I find some obstacles:
1. This data is single-end, but there are two index files (`Smartseq3.HEK.fwdprimer.index1.fastq.gz` and `Smartseq3.HEK.fwdprimer.index2.fastq.gz`). Do I need to input both of them for zUMI?
2. The `yaml` file and `expected_barcodes.txt` file are not accessible. Where could I get them?

Thanks

**Comment by cziegenhain** [comment]
Hi,

Yes you need both index files, the data is single-end but dual-index.
You can find the barcode annotation in ArrayExpress too: https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-8735/E-MTAB-8735.processed.2.zip/Smartseq3.HEK.fwdprimer.sample_annotation.txt
To create a yaml file for zUMIs, please check the documentation of the pipeline: https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup

Best,
Christoph

**Comment by yewero** [comment]
Thanks. But when I ran the code, an error occurred:
`bash zUMIs/zUMIs.sh -y test.yaml`

> [E::sam_parse1] incomplete aux field
> [W::sam_read1] parse error at line 2
> [main_samview] truncated file.

I found this error was caused by the missing `UB` and `QU` in the sam file produced by the `fqfilter_v2.pl` file:
https://github.com/sdparekh/zUMIs/blob/5358e43e00dc55289cef4a599891ca3cf040defd/fqfilter_v2.pl#L104

For example (the first row in zUMIs_output/.tmpMerge/HEK293T.HEK293Taa.filtered.tagged.bam):

> NB502120:185:HHFCMBGXF:1:11101:6213:1051        4       *       0       0       *       *       0       0       GTATTNTGAGAAGCCATGCCGCCGGCGACAGAGGGAAANCTATGAAANGTNCNNGNGGATCTNCNACNNGGAANT  AAAAA#EE/EEEEEEEEEEEEEEEEEEAEEEEEEEEEE#EAEEEEEE#AE#E##E#EEEEEE#E#EE##EEEE#E      BC:Z:AAGAGACGNCTCTCTN   UB:Z:     QB:Z:AAAAAEEE#AAAAEE#   QU:Z:

Input file information:
1. test.yaml:

> project: HEK293T
> sequence_files:
>   file1:
>     name: /home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/01-cleandata/Smartseq3.HEK.fwdprimer.read1.fastq.gz
>     base_definition:
>       - cDNA(23-75)
>       - UMI(12-19)
>     find_pattern: ATTGCGCAATG
>   file2:
>     name: /home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/01-cleandata/Smartseq3.HEK.fwdprimer.index1.fastq.gz
>     base_definition:
>       - BC(1-8)
>   file3:
>     name: /home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/01-cleandata/Smartseq3.HEK.fwdprimer.index2.fastq.gz
>     base_definition:
>       - BC(1-8)
> reference:
>   STAR_index: /home/XXX/users/YYY/Smart-seq3/Genomes/human_v32/STAR_index
>   GTF_file: /home/XXX/users/YYY/Smart-seq3/Genomes/human_v32/genes.gtf
>   additional_STAR_params: '--limitSjdbInsertNsj 2000000 --outFilterIntronMotifs --RemoveNoncanonicalUnannotated --clip3pAdapterSeq CTGTCTCTTATACACATCT'
> out_dir: /home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression
> num_threads: 10
> mem_limit: null
> filter_cutoffs:
>   BC_filter:
>     num_bases: 3
>     phred: 20
>   UMI_filter:
>     num_bases: 2
>     phred: 20
> barcodes:
>   barcode_num: ~
>   barcode_file: /home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/data/expected_barcodes.txt
>   automatic: no
>   BarcodeBinning: 1
>   nReadsperCell: 100
>   demultiplex: no
> counting_opts:
>   introns: yes
>   downsampling: '0'
>   strand: 0
>   Ham_Dist: 1
>   write_ham: no
>   velocyto: no
>   primaryHit: yes
>   twoPass: no
> make_stats: yes
> which_Stage: Filtering
> samtools_exec: samtools
> pigz_exec: pigz
> STAR_exec: STAR
> Rscript_exec: Rscript
> zUMIs_directory: /lustre1/XXX/users/YYY/Tools/zUMIs
> read_layout: SE
> 

2. Barcode list (expected_barcodes.txt):
The 6th column of the sample annotation table (https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-8735/E-MTAB-8735.processed.2.zip/Smartseq3.HEK.fwdprimer.sample_annotation.txt) excluding the first row.

Software version:

> zUMIs 2.9.4d
> samtools v1.2

**Comment by cziegenhain** [comment]
Hi again,

No, the fqfilter script should report empty UMI & UMI quality tags when the read is an internal fragment, so this is not the source of the error.
To troubleshoot I would need the full verbose of the pipeline.

**Comment by yewero** [comment]
Hi, here is the verbose:
> 
> 
>  You provided these parameters:
>  YAML file:     test.yaml
>  zUMIs directory:               /lustre1/XXX/users/YYY/Tools/zUMIs
>  STAR executable                STAR
>  samtools executable            samtools
>  pigz executable                pigz
>  Rscript executable             Rscript
>  RAM limit:   null
>  zUMIs version 2.9.4d
> 
> 
> Sat Oct 31 14:48:56 CST 2020
> WARNING: The STAR version used for mapping is 2.5.3a and the STAR index was created using the version 20201. This may lead to an error while mapping. If you encounter any errors at the mappi
> ng stage, please make sure to create the STAR index using STAR 2.5.3a.
> Filtering...
> [E::sam_parse1] incomplete aux field
> [W::sam_read1] parse error at line 2
> [main_samview] truncated file.
> cat: /home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression/zUMIs_output/.tmpMerge//HEK293T.*.BCstats.txt: No such file or directory
> Sat Oct 31 14:48:57 CST 2020
> Warning message:
> package ‘data.table’ was built under R version 3.5.3
> Error in eval(bysub, parent.frame(), parent.frame()) :
>   object 'XC' not found
> Calls: cellBC -> [ -> [.data.table -> eval -> eval
> In addition: Warning message:
> In data.table::fread(bccount_file, header = FALSE, col.names = c("XC",  :
>   File '/home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression/HEK293T.BCstats.txt' has size 0. Returning a NULL data.table.
> Execution halted
> Mapping...
> Warning message:
> package ‘data.table’ was built under R version 3.5.3
> [1] "2020-10-31 14:48:59 CST"
> Warning message:
> In data.table::fread(cmd = paste(samtools, "view", filtered_bams[1],  :
>   File '/tmp/Rtmpt4mpeM/file4949578fffdcb' has size 0. Returning a NULL data.table.
> 
> EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "readFilesType" in input "Command-Line-Initial"
> SOLUTION: use correct parameter name (check the manual)
> 
> Oct 31 14:49:02 ...... FATAL ERROR, exiting
> 
> EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "readFilesType" in input "Command-Line-Initial"
> SOLUTION: use correct parameter name (check the manual)
> 
> Oct 31 14:49:02 ...... FATAL ERROR, exiting
> 
> EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "readFilesType" in input "Command-Line-Initial"
> SOLUTION: use correct parameter name (check the manual)
> 
> Oct 31 14:49:02 ...... FATAL ERROR, exiting
> Usage: samtools cat [-h header.sam] [-o out.bam] <in1.bam> <in2.bam> [...]
> Usage: samtools cat [-h header.sam] [-o out.bam] <in1.bam> <in2.bam> [...]
> Usage: samtools cat [-h header.sam] [-o out.bam] <in1.bam> <in2.bam> [...]
> rm: cannot remove ‘/home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression/zUMIs_output/.tmpMap/tmp.HEK293T.*’: No such file or directory
> Sat Oct 31 14:49:02 CST 2020
> Counting...
> Warning message:
> package ‘data.table’ was built under R version 3.5.3
> Warning message:
> package ‘dplyr’ was built under R version 3.5.3
> [1] "2020-10-31 14:49:16 CST"
> Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes_binned.txt")) :
>   File '/home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression/zUMIs_output/HEK293Tkept_barcodes_binned.txt' does not exist or is non-readable. getwd()=='/lustre1/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression'
> Execution halted
> Sat Oct 31 14:49:17 CST 2020
> Loading required package: yaml
> Loading required package: Matrix
> [1] "loomR found"
> Error in gzfile(file, "rb") : cannot open the connection
> Calls: rds_to_loom -> readRDS -> gzfile
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression/zUMIs_output/expression/HEK293T.dgecounts.rds', probable reason 'No such file or directory'
> Execution halted
> Sat Oct 31 14:49:20 CST 2020
> Descriptive statistics...
> [1] "I am loading useful packages for plotting..."
> [1] "2020-10-31 14:49:21 CST"
> Warning message:
> package ‘data.table’ was built under R version 3.5.3
> Warning message:
> package ‘dplyr’ was built under R version 3.5.3
> Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  :
>   File '/home/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression/zUMIs_output/HEK293Tkept_barcodes.txt' does not exist or is non-readable. getwd()=='/lustre1/XXX/users/YYY/Smart-seq3/datasets/C5_SMART-seq3/02-expression'
> Execution halted
> Sat Oct 31 14:49:30 CST 2020
>

**Comment by yewero** [comment]
Interestingly, this step works for `samtools v1.11`.
