### ISSUE TITLE
Remove `--quantMode TranscriptomeSAM'` from example YAML config

### ISSUE THREAD

**Issue by ghuls** [sandberg-lab/Smart-seq3#7]
Remove `--quantMode TranscriptomeSAM'` from example YAML config:
https://github.com/sandberg-lab/Smart-seq3/blob/master/allele_level_expression/mouse_cross.yaml#L24

As that parameter is automatically added by zUMI and STAR will complain about the fact that the parameter is added twice.

**Comment by cziegenhain** [comment]
Thats true, the default changed there. I updated accordingly, thanks!
