### ISSUE TITLE
New Error - getting Parse error 

### ISSUE THREAD

**Issue by Kdoganyi** [sandberg-lab/Smart-seq3#9]
Hi there! I have a new issue that I just started getting a few days ago.  Basically, after getting some analysis done, and getting some data out, I stopped making any process. The issue is that now when I run the program (zUMIs/zUMIs.sh -y 'location') the program keeps halting at the first stage, saying there was a parse error and from there on I am getting empty files. Below I pasted what I get as a warning
"
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
cat: /public/groups/hausslerlab/people/kivilcim/iMGL/outputall/zUMIs_output/.tmpMerge//KDiMGLall.*.BCstats.txt: No such file or directory
Mon Mar 14 20:24:07 PDT 2022
Error in eval(bysub, parent.frame(), parent.frame()) :
object 'XC' not found
Calls: cellBC -> [ -> [.data.table -> eval -> eval
In addition: Warning message:
In data.table::fread(bccount_file, header = FALSE, col.names = c("XC", :
File '/public/groups/hausslerlab/people/kivilcim/iMGL/outputall/KDiMGLall.BCstats.txt' has size 0. Returning a NULL data.table.
Execution halted
"
This did not happen when I was using the same data 2 days ago, and my yaml file appears to be formatted correctly. I have seen some comments about this issue in the zUMIs repository, but even the code changes recommended appears to be actually corrected in my version. I am attaching my yamly file. I can also attach one of my fastq files if you prefer, to my understanding the error is complaining because there is no header in the fastq but what is interesting to me is that this was not happening previously. 
[KDiMGLsp_yaml.txt](https://github.com/sandberg-lab/Smart-seq3/files/8275736/KDiMGLsp_yaml.txt)
Truly appreciative of your help! Thank you so much!

**Comment by cziegenhain** [comment]
Hi,

If the input data is identical and the YAML file has the correct paths to the input files, I would recommend to just clone zUMIs again from GitHub in case you accidentally changed something during testing.
Even though zUMIs overwrites all existing files with identical names in the specified output directory, it doesn't hurt to point to an empty folder for output.

Lastly, can you post the first few lines of each or your fastq read files?

If I remember right from your previous post, this was a MiSeq run, so maybe ~20 million reads or so? I would expect that to finish easily in under 1 hour.

**Comment by Kdoganyi** [comment]
Hi there, I am trying deleting zUMIs and uploading it again, but here are first a few lines on my concatinated fastq files. 
R1:
@M00160:13:000000000-JVJJM:1:1101:15242:1339 1:N:0:TAAGGCG+TATCCTC
AGATACTTTTCTGGGACATTTCTAGCTTTATTTTTGCAGGATGTATAAATACAATATTTTGCAAAACACTTGAAGACAAAAAAGAATGTAAACTGTCTCTTATACACATCTCCGAGCCCACGAGACTAAGGCGAATCTCGTATGCCGTCT
+
BBCCCFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHGHHHHGHHHHHHGHHHHHHHHHIHIHHHIGHHHHHHHHHHHHHHHHHGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGHGGGGGGHGHHHHGFGF/FGHGGHHHHGGGH
@M00160:13:000000000-JVJJM:1:1101:15888:1340 1:N:0:TAAGGCG+TATCCTC
AGCTGAGATAAACTTACACTGGCATACCCTGTTTTATTGTGTGTTGATTTATTGCTGTCTCTTATACACATCTCCGAGCCCACGAGACTAAGGCGAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAAGAAGACACGATGTAACA
+
A3AABFFFFFFFGGGGGGGGGGFHHHHHHGHGHHHHHHHHHHFGGHHHHHHHHHHHHHHHHGHHHHHHHHGHHHHGGGGGGHGGGGGGHFHHHHGGGGAHHHGGHHGGGGGHGHHHHHHF0GFHHG?@BB//-..00100<.-.<<000<
@M00160:13:000000000-JVJJM:1:1101:15311:1343 1:N:0:TAAGGCG+TATCCTC
ATTCGTAGTAGCCAAAAAATGGAAACAGCTCAAATGCCCATCAACTGACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCGTATGCTGCCTGTCTTTTATAAAAAACTCCGAGCCAACAAAAAAAAAGCGAAAATCGTATGGCCTCTTC
+
AAAAA1CA1D@FEGGGGGGGGCFFHHHHGHHHHHHHHHHHHHHGFHHHHFEEGGHGGEGGCEEECG?EGCGGGGGGGGC.<C<../0000C00;/000:00:000:-.000.;-9-//....:.-;--------9//---//--/;-9//
@M00160:13:000000000-JVJJM:1:1101:15531:1346 1:N:0:TAAGGCG+TATCCTC
CAGAGGGGCTGTGCGAGAGGTGGTGGGTGGCCAAGGAGGGAGCCAAGAGACCAAGTTCCGGCCAAAGGGTCAGAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACTAAGGCGAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAA

R2:


@M00160:13:000000000-JVJJM:1:1101:15242:1339 2:N:0:TAAGGCG+TATCCTC
TTTACATTCTTTTTTGTCTTCAAGTGTTTTGCAAAATATTGTATTTATACATCCTGCAAAAATAAAGCTAGAAATGTCCCAGAAAAGTATCTCTGTCTCTTATACACATCTGACGCTGCCGACGAAGAGGATAGTGTAGATTTCGGTGGG
+
CCCCCFFFFFFFGGGGGGGGGFHHFGGHHHHGHHGHHHHHHHHHHHHHHHHHHFGHHEGFHHHHHHHHHHGFFHHHHHHHHHGGHGHHHHHHHHHHHHHHHHHHHHHHHHHGHHGGGGGHGGGGGGFGHHHB3CHHFE3333?32>/<B/
@M00160:13:000000000-JVJJM:1:1101:15888:1340 2:N:0:TAAGGCG+TATCCTC
CAATAAATCAACACACAATAAAACAGGGTATGCCAGTGTAAGTTTATCTCAGCTCTGTCTCTTATACACATCTGACGCTGCCGACGAAGAGGATAGTGGAGATCTCGGTGGTCGCCGTATCATTAAAAAAAAAAAAAGATCCAGATAGAG
+
CCCCCFFFFFFFGGGGGGGGGGHHHHHGGGHHHHGHFGGHHHGHHHHHHHHGGHHHHHHHGHHHHHHHHHHHHGHHGGGGGHGGGGGGFGHHHGHHHF13F3B3@41FFGE>?/><<</003??333BGDCF/<->-..0000<<0<000
@M00160:13:000000000-JVJJM:1:1101:15311:1343 2:N:0:TAAGGCG+TATCCTC
GCAGCATACGATTTTTTTTTTTTTTTTTTTTTTTTTTTTTCGTCAGTTGATGGGCATTTGGGTTGTTTCCTTTTTTTGGCTACTACGAATTTTTCTCTTATACATATTTGACGTTGCCGACGAAGAGGATAGTTTTGATTCTGGGGGGGG
+
>BB>BCFFFFBBGGGGGGGGGGGGGGGGGGGGGGGGGGGG2<?///22222@=F000?F11?/>-<GG111>FGHGF--0<:/<00<.:..:00/<0<C0000000<0::00.....<<----<...../000000..<B000</-9---
@M00160:13:000000000-JVJJM:1:1101:15531:1346 2:N:0:TAAGGCG+TATCCTC
CTCTGACCCTTTGGCCGGAACTTGGTCTCTTGGCTCCCTCCTTGGCCACCCACCACCTCTCGCACAGCCCCTCTGCTGTCTCTTATACACATCTGACGCTGCCGACGAAGAGGATAGTGGAGATCTCGGGGGTCGCCGGATCATTAAAAA
+
?ABBBFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHGCGGGHHHHHHHGHGGGGHHGHHHHGGGGGFHHGGHGHHHHHHHHHHHHHGHHGHHHHHHHGGGGGHFGGGGGGGHGAFFHGF02/<F2FHFA/<--.<-C@--:-:0C0:;0:
@M00160:13:000000000-JVJJM:1:1101:15233:1365 2:N:0:TAAGGCG+TATCCTC
TCCCAAGACCTGCCAGCAGAGAGGGCTGTGTGTCCTCAGAGCCCTGTCTCTTATACACATCTGACGCTGCCGACGAAGAGGATAGTGTAGATCTCGGGGGTCGCCGTGTCATTTAAAAAAAAAAAAAAAAAGTAGTGAGAGAAAGTGAAA




I1:


@M00160:13:000000000-JVJJM:1:1101:15242:1339 1:N:0:TAAGGCG+TATCCTC
TAAGGCG
+
CBCCCFD
@M00160:13:000000000-JVJJM:1:1101:15888:1340 1:N:0:TAAGGCG+TATCCTC
TAAGGCG
+
DCDDDFD
@M00160:13:000000000-JVJJM:1:1101:15311:1343 1:N:0:TAAGGCG+TATCCTC
TAAGGCG
+
A1A>AFD
@M00160:13:000000000-JVJJM:1:1101:15531:1346 1:N:0:TAAGGCG+TATCCTC
TAAGGCG
+
CCBCCFE
@M00160:13:000000000-JVJJM:1:1101:15233:1365 1:N:0:TAAGGCG+TATCCTC
TAAGGCG


I2:

@M00160:13:000000000-JVJJM:1:1101:15242:1339 2:N:0:TAAGGCG+TATCCTC
TATCCTC
+
CDDDDFF
@M00160:13:000000000-JVJJM:1:1101:15888:1340 2:N:0:TAAGGCG+TATCCTC
TATCCTC
+
CBCCCFF
@M00160:13:000000000-JVJJM:1:1101:15311:1343 2:N:0:TAAGGCG+TATCCTC
TATCCTC
+
CCCCCFF
@M00160:13:000000000-JVJJM:1:1101:15531:1346 2:N:0:TAAGGCG+TATCCTC
TATCCTC
+
CCDDDFF

**Comment by Kdoganyi** [comment]
I tried deleting and reuploading zUMIs however I am still getting the same problem

**Comment by Kdoganyi** [comment]
> Hi,
> 
> If the input data is identical and the YAML file has the correct paths to the input files, I would recommend to just clone zUMIs again from GitHub in case you accidentally changed something during testing. Even though zUMIs overwrites all existing files with identical names in the specified output directory, it doesn't hurt to point to an empty folder for output.
> 
> Lastly, can you post the first few lines of each or your fastq read files?
> 
> If I remember right from your previous post, this was a MiSeq run, so maybe ~20 million reads or so? I would expect that to finish easily in under 1 hour.

***Hi there I wanted to make sure you saw my earlier messages?***

**Comment by cziegenhain** [comment]
I'd say the fastq files look totally normal.

Most confusing for me is that you write it was working first but then not anymore with the same files - that doesn't seem very plausible.

Feel free to upload the data and I can see if the error is reproducible.

**Comment by Kdoganyi** [comment]
> 

hi there, I am truly sorry for this late reply.  Is it possible for me to send you the files through an email, my email address is kdoganyi@ucsc.edu  I would be very happy if you could also check it.

**Comment by cziegenhain** [comment]
Hi,

I identified the source of your error.
You are giving a barcode range of BC(1-8) but your barcode reads contain only 7 bases each.

The annotated barcodes from your allow list are also not found in the data, so you may want to double-check this.

Best,
Christoph


> project: KDiMGLall
> sequence_files:
>   file1:
>     name: /home/chris/projects/kdoganyi/iMGLR1.fastq.gz
>     base_definition:
>     - cDNA(23-150)
>     - UMI(12-19)
>     find_pattern: ATTGCGCAATG
>   file2:
>     name: /home/chris/projects/kdoganyi/iMGLR2.fastq.gz
>     base_definition: cDNA(1-150)
>   file3:
>     name: /home/chris/projects/kdoganyi/CNT_iMGL_I1_001.fastq.gz
>     base_definition: BC(1-7)
>   file4:
>     name: /home/chris/projects/kdoganyi/CNT_iMGL_I2_001.fastq.gz
>     base_definition: BC(1-7)
> reference:
>   STAR_index: /home/chris/resources/genomes/Human/STAR7idx_primary_noGTF/
>   GTF_file: /home/chris/resources/genomes/Human/Homo_sapiens.GRCh38.95.chr.gtf
>   additional_STAR_params: '--clip3pAdapterSeq CTGTCTCTTATACACATCT'
>   exon_extension: no
>   extension_length: 0
>   scaffold_length_min: 0
> out_dir: /home/chris/projects/kdoganyi/out
> num_threads: 20
> mem_limit: 40
> filter_cutoffs:
>   BC_filter:
>     num_bases: 3
>     phred: 20
>   UMI_filter:
>     num_bases: 2
>     phred: 20
> barcodes:
>   barcode_num: null
>   barcode_file: /home/chris/projects/kdoganyi/iMGL_NexteraBarcodes.txt
>   barcode_sharing: null
>   automatic: no
>   BarcodeBinning: 1
>   nReadsperCell: 100
>   demultiplex: yes
> counting_opts:
>   introns: yes
>   downsampling: '0'
>   strand: 1
>   Ham_Dist: 1
>   velocyto: no
>   primaryHit: yes
>   twoPass: no
> make_stats: yes
> which_Stage: Filtering
>

**Comment by Kdoganyi** [comment]
Hi Christoph,
Thank you so much for looking into this. It is interesting that none of the
barcodes are present. I previously realized that by manually checking each
barcode. Do you know what may have done wrong? My guess was towards the
data being a miseq data. However, I used the SmartSeq3 method and generated
the barcodes by using Nextera. Have you ever seen a case where none of the
whitelist members are actually found in the data? Should I be worried?
Thank you so much, for your help. I am truly grateful.
Warm Regards,
Kivilcim

**Comment by cziegenhain** [comment]
Well I don’t think there is any kind of complicated mystery here - your annotated BCs are 16bp in total but your reads contain 14bp only!
